import { MidnightBech32m, UnshieldedAddress } from "@midnight-ntwrk/wallet-sdk-address-format";
import { nativeToken } from "@midnight-ntwrk/ledger-v8";
import { setNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import { EnvironmentManager } from "./environment.js";
import { treasurySecret, type TreasuryName } from "./fund-deposit.js";
import { buildWallet, currentState, deriveKeys, waitForSync } from "./wallet.js";
import type { NetworkConfig } from "../providers/midnight-providers.js";

/**
 * Giving the treasury wallets the NIGHT they need to spend what they hold.
 *
 * ── The problem this exists for ─────────────────────────────────────────────
 *
 * A treasury only ever RECEIVES. `remitTax` and `remitSocial` send it pEUR and
 * nothing sends it NIGHT, so its ordinary state is a balance it cannot move:
 * fees are paid in DUST, DUST is generated by registered NIGHT UTXOs, and a
 * wallet with no NIGHT has neither. The failure surfaces from deep inside the
 * balancer as `Insufficient funds for fallible segment N` — a segment number
 * and no wallet — which is not a sentence anyone can act on.
 *
 * ── Why it cannot be done by hand ───────────────────────────────────────────
 *
 * The obvious fix is to open the treasury in a wallet app and use the faucet.
 * That is not possible: `TAX_TREASURY_SEED` and `SOCIAL_TREASURY_SEED` are
 * 64-character raw hex seeds, and a browser wallet (Lace, IAM) imports a BIP-39
 * recovery phrase and nothing else. There is no phrase for these seeds — they
 * were never derived from one — so no wallet app can hold them.
 *
 * This service can, because it already holds them to sign remittances. So the
 * platform wallet, which has NIGHT, sends some to each treasury, and each
 * treasury then registers what it received.
 *
 * ── Both halves are required ────────────────────────────────────────────────
 *
 * Sending NIGHT is not enough on its own. A NIGHT UTXO generates DUST only once
 * it is REGISTERED for generation, so a wallet holding unregistered NIGHT still
 * cannot pay a fee, and would fail in exactly the same way as one holding
 * none. Registration is self-funding — it pays its own fee out of the DUST the
 * registered UTXOs generate — so it works from a zero DUST balance, which is
 * the only balance a freshly-funded treasury has.
 */

const NIGHT = nativeToken().raw;

/** Enough to register and then pay fees for a long while. Overridable per call. */
export const DEFAULT_NIGHT_PER_TREASURY = 5_000_000n;

export interface TreasuryFunding {
  from: TreasuryName;
  address: string;
  /** Set when NIGHT was sent to this treasury in this run. */
  transferTx?: string;
  /** Set when its NIGHT UTXOs were registered for DUST generation. */
  registerTx?: string;
  /** Set instead of the above when nothing needed doing, or when it failed. */
  note?: string;
}

/** A treasury's unshielded address, derived offline — no wallet, no sync. */
function addressOf(from: TreasuryName, network: NetworkConfig): string {
  return deriveKeys(treasurySecret(from), network.networkId)
    .unshieldedKeystore.getBech32Address()
    .toString();
}

export async function fundTreasuriesWithNight(options?: {
  wallets?: TreasuryName[];
  /** NIGHT per treasury, in its smallest unit. */
  amount?: bigint;
  /**
   * Send NIGHT even to a treasury that already holds some.
   *
   * Off by default: this is setup, not a top-up, and running it twice should
   * not quietly move NIGHT every time an operator presses a button.
   */
  force?: boolean;
  log?: (line: string) => void;
}): Promise<TreasuryFunding[]> {
  const targets = options?.wallets ?? (["social-treasury", "tax-treasury"] as TreasuryName[]);
  const amount = options?.amount ?? DEFAULT_NIGHT_PER_TREASURY;
  const log = options?.log ?? (() => {});

  const network = EnvironmentManager.getNetworkConfig();
  setNetworkId(network.networkId);

  const results: TreasuryFunding[] = targets.map((from) => ({
    from,
    address: addressOf(from, network),
  }));

  // ── Which of them actually need NIGHT ────────────────────────────────────
  //
  // Asked before the platform wallet is built, so a run where nothing is needed
  // costs one sync per treasury rather than one for the platform as well.
  const needing: TreasuryFunding[] = [];
  for (const result of results) {
    const wallet = await buildWallet(treasurySecret(result.from), network);
    try {
      log(`Checking the ${result.from} wallet…`);
      await waitForSync(wallet, (line) => log(`   ${line}`));
      const state = await currentState(wallet);
      const held = ((state.unshielded as any).balances ?? {})[NIGHT] ?? 0n;
      if (held > 0n && !options?.force) {
        log(`   ${result.from} already holds NIGHT — leaving it alone`);
        result.note = "already holds NIGHT";
        // Registration is still worth attempting: NIGHT that was never
        // registered generates no DUST, and holding it is indistinguishable
        // from holding none when a fee has to be paid.
        needing.push(result);
        result.note = "already holds NIGHT — checking its registration only";
      } else {
        needing.push(result);
      }
    } finally {
      await wallet.facade.stop();
    }
  }

  const toSend = needing.filter((r) => !r.note);
  if (toSend.length > 0) {
    await sendNight(toSend, amount, network, log);
    // The UTXOs are visible before the intent that created them has settled,
    // and a registration built against an unsettled UTXO is refused. The retry
    // in `registerFor` covers the rest; this simply stops the first attempt
    // being one that is certain to fail.
    log("Waiting for the transfer to settle…");
    await new Promise((resolve) => setTimeout(resolve, 30_000));
  }

  // ── Register, one wallet at a time ───────────────────────────────────────
  for (const result of needing) {
    try {
      await registerFor(result, network, log);
    } catch (cause) {
      const message = cause instanceof Error ? cause.message : String(cause);
      log(`   ${result.from}: registration failed — ${message}`);
      result.note = `registration failed: ${message}`;
    }
  }

  return results;
}

/**
 * One transaction carrying every treasury's NIGHT.
 *
 * `transferTransaction` takes an array of outputs, so this is one fee and one
 * signature rather than one per treasury — and it is atomic, which matters more
 * than the fee: a run that funded the tax treasury and then failed on the
 * social one would leave the operator to work out which half to repeat.
 */
async function sendNight(
  targets: TreasuryFunding[],
  amount: bigint,
  network: NetworkConfig,
  log: (line: string) => void
): Promise<void> {
  const platform = await buildWallet(EnvironmentManager.getWalletSecret(), network);
  try {
    log("Syncing the platform wallet…");
    await waitForSync(platform, (line) => log(`   ${line}`));

    const state = await currentState(platform);
    const held = ((state.unshielded as any).balances ?? {})[NIGHT] ?? 0n;
    const total = amount * BigInt(targets.length);
    if (held < total) {
      throw new Error(
        `The platform wallet holds ${held} NIGHT, which does not cover ${total} for ` +
          `${targets.length} treasur${targets.length === 1 ? "y" : "ies"}. Fund it at ` +
          `${network.faucet || "the network's faucet"} first.`
      );
    }

    const outputs = targets.map((target) => ({
      type: NIGHT,
      receiverAddress: MidnightBech32m.parse(target.address).decode(
        UnshieldedAddress,
        network.networkId as never
      ),
      amount,
    }));

    log(`Sending ${amount} NIGHT to ${targets.map((t) => t.from).join(" and ")}…`);
    const recipe = await platform.facade.transferTransaction(
      [{ type: "unshielded" as const, outputs }],
      {
        shieldedSecretKeys: platform.shieldedSecretKeys,
        dustSecretKey: platform.dustSecretKey,
      },
      { ttl: new Date(Date.now() + 60 * 60 * 1000) }
    );
    const signed = await platform.facade.signRecipe(recipe, (data) =>
      platform.keys.unshieldedKeystore.signData(data)
    );
    const finalized = await platform.facade.finalizeRecipe(signed);
    const txId = await platform.facade.submitTransaction(finalized as any);
    log(`   sent: ${txId}`);
    for (const target of targets) target.transferTx = String(txId);
  } finally {
    await platform.facade.stop();
  }
}

/**
 * Registers a treasury's NIGHT so it starts generating DUST.
 *
 * The UTXOs have to be VISIBLE to the receiving wallet first, which is not the
 * same moment as the transfer being submitted — so this waits for them rather
 * than reading once and reporting "no NIGHT" about money that is on its way.
 */
async function registerFor(
  result: TreasuryFunding,
  network: NetworkConfig,
  log: (line: string) => void
): Promise<void> {
  const wallet = await buildWallet(treasurySecret(result.from), network);
  try {
    log(`Registering the ${result.from} wallet's NIGHT for DUST…`);

    let utxos: readonly any[] = [];
    const deadline = Date.now() + 5 * 60 * 1000;
    for (;;) {
      await waitForSync(wallet, () => {});
      const state = await currentState(wallet);
      const all = (state.unshielded as any).availableCoins as readonly any[];
      // Only the ones not already generating. Re-registering an existing
      // registration is a fee for nothing.
      utxos = all.filter(
        (u) => u.utxo?.type === NIGHT && !u.meta?.registeredForDustGeneration
      );
      if (utxos.length > 0) break;
      if (all.some((u) => u.utxo?.type === NIGHT)) {
        log(`   ${result.from}: its NIGHT is already registered`);
        result.note = result.note ?? "NIGHT already registered";
        return;
      }
      if (Date.now() > deadline) {
        throw new Error("its NIGHT did not arrive within five minutes");
      }
      await new Promise((resolve) => setTimeout(resolve, 5000));
    }

    const { fee } = await wallet.facade.estimateRegistration(utxos);
    log(`   ${utxos.length} UTXO(s), estimated registration fee ${fee}`);
    // Registration pays its own fee out of the DUST the registered UTXOs
    // generate, so it has to wait for that much to have been generated before
    // it can be built — a fresh wallet's DUST balance is zero.
    await wallet.facade.waitForGeneratedDust(utxos, fee);

    /**
     * Retried, because the first attempt races the transfer that created these
     * UTXOs.
     *
     * They become VISIBLE to this wallet before the intent that produced them
     * has settled, so a registration built immediately is rejected — and
     * rejected as a bare `Transaction submission error`, with the Effect
     * failure carrying nothing underneath it. The same registration, built
     * again a few seconds later, is accepted. Measured, not assumed: the run
     * that failed here succeeded unchanged on the next attempt.
     *
     * The recipe is rebuilt each time rather than resubmitted. It is bound to
     * the state it was proved against, so retrying the same finalized
     * transaction would fail for a second, different reason.
     */
    let lastError: unknown = null;
    for (let attempt = 1; attempt <= 3; attempt += 1) {
      try {
        const recipe = await wallet.facade.registerNightUtxosForDustGeneration(
          utxos,
          wallet.keys.unshieldedKeystore.getPublicKey(),
          (payload) => wallet.keys.unshieldedKeystore.signData(payload)
        );
        const finalized = await wallet.facade.finalizeRecipe(recipe);
        const txId = await wallet.facade.submitTransaction(finalized as any);
        result.registerTx = String(txId);
        log(`   registered: ${txId}`);
        return;
      } catch (cause) {
        lastError = cause;
        const message = cause instanceof Error ? cause.message : String(cause);
        if (attempt === 3) break;
        log(`   attempt ${attempt} refused (${message}) — retrying in 20s`);
        await new Promise((resolve) => setTimeout(resolve, 20_000));
        await waitForSync(wallet, () => {});
      }
    }
    throw lastError instanceof Error ? lastError : new Error(String(lastError));
  } finally {
    await wallet.facade.stop();
  }
}
